<a href="https://colab.research.google.com/github/harshshaw/Flask-Apis-for-Hackathon/blob/main/Copy_of_Boltzmann_Machine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Boltzmann Machine

##Downloading the dataset

###ML-100K

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
!wget "http://files.grouplens.org/datasets/movielens/ml-1m.zip"
!unzip ml-1m.zip
!ls

--2021-06-24 12:54:09--  http://files.grouplens.org/datasets/movielens/ml-1m.zip
Resolving files.grouplens.org (files.grouplens.org)... 128.101.65.152
Connecting to files.grouplens.org (files.grouplens.org)|128.101.65.152|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5917549 (5.6M) [application/zip]
Saving to: ‘ml-1m.zip.7’

ml-1m.zip.7         100%[===================>]   5.64M  6.85MB/s    in 0.8s    

2021-06-24 12:54:10 (6.85 MB/s) - ‘ml-1m.zip.7’ saved [5917549/5917549]

Archive:  ml-1m.zip
replace ml-1m/movies.dat? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: ml-1m/movies.dat        
  inflating: ml-1m/ratings.dat       
  inflating: ml-1m/README            
  inflating: ml-1m/users.dat         
ml-100k        ml-100k.zip.2  ml-1m.zip.1  ml-1m.zip.4	ml-1m.zip.7
ml-100k.zip    ml-1m	      ml-1m.zip.2  ml-1m.zip.5	sample_data
ml-100k.zip.1  ml-1m.zip      ml-1m.zip.3  ml-1m.zip.6


In [ ]:
movies = pd.read_csv('ml-1m/movies.dat', sep = '::', header = None, engine = 'python', encoding = 'latin-1')
users = pd.read_csv('ml-1m/users.dat', sep = '::', header = None, engine = 'python', encoding = 'latin-1')
ratings = pd.read_csv('ml-1m/ratings.dat', sep = '::', header = None, engine = 'python', encoding = 'latin-1')
movies.columns=(['movieId','title','Genre'])
ratings.columns=(['userId','movieId','rating','timestamp'])
movies.head()

movieId                               title                         Genre
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy

In [ ]:

movies_df =movies 
''' pd.read_csv('movies.csv',usecols=['movieId','title'],dtype={'movieId': 'int32', 'title': 'str'}) '''
rating_df=ratings
''' pd.read_csv('ratings.csv',usecols=['userId', 'movieId', 'rating'],
    dtype={'userId': 'int32', 'movieId': 'int32', 'rating': 'float32'}) '''

" pd.read_csv('ratings.csv',usecols=['userId', 'movieId', 'rating'],\n    dtype={'userId': 'int32', 'movieId': 'int32', 'rating': 'float32'}) "

In [ ]:
movies_df.head()

movieId                               title                         Genre
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy

In [ ]:
rating_df.head()

userId  movieId  rating  timestamp
0       1     1193       5  978300760
1       1      661       3  978302109
2       1      914       3  978301968
3       1     3408       4  978300275
4       1     2355       5  978824291

In [ ]:

df = pd.merge(rating_df,movies_df,on='movieId')
df.head()

userId  movieId  ...                                   title  Genre
0       1     1193  ...  One Flew Over the Cuckoo's Nest (1975)  Drama
1       2     1193  ...  One Flew Over the Cuckoo's Nest (1975)  Drama
2      12     1193  ...  One Flew Over the Cuckoo's Nest (1975)  Drama
3      15     1193  ...  One Flew Over the Cuckoo's Nest (1975)  Drama
4      17     1193  ...  One Flew Over the Cuckoo's Nest (1975)  Drama

[5 rows x 6 columns]

In [ ]:
combine_movie_rating = df.dropna(axis = 0, subset = ['title'])
movie_ratingCount = (combine_movie_rating.
     groupby(by = ['title'])['rating'].
     count().
     reset_index().
     rename(columns = {'rating': 'totalRatingCount'})
     [['title', 'totalRatingCount']]
    )
movie_ratingCount.head()

title  totalRatingCount
0         $1,000,000 Duck (1971)                37
1           'Night Mother (1986)                70
2      'Til There Was You (1997)                52
3             'burbs, The (1989)               303
4  ...And Justice for All (1979)               199

In [ ]:
rating_with_totalRatingCount = combine_movie_rating.merge(movie_ratingCount, left_on = 'title', right_on = 'title', how = 'left')
rating_with_totalRatingCount.head()

userId  movieId  ...  Genre  totalRatingCount
0       1     1193  ...  Drama              1725
1       2     1193  ...  Drama              1725
2      12     1193  ...  Drama              1725
3      15     1193  ...  Drama              1725
4      17     1193  ...  Drama              1725

[5 rows x 7 columns]

In [ ]:
pd.set_option('display.float_format', lambda x: '%.3f' % x)
print(movie_ratingCount['totalRatingCount'].describe())

count   3706.000
mean     269.889
std      384.048
min        1.000
25%       33.000
50%      123.500
75%      350.000
max     3428.000
Name: totalRatingCount, dtype: float64


In [ ]:

popularity_threshold = 50
rating_popular_movie= rating_with_totalRatingCount.query('totalRatingCount >= @popularity_threshold')
rating_popular_movie.head()

userId  movieId  ...  Genre  totalRatingCount
0       1     1193  ...  Drama              1725
1       2     1193  ...  Drama              1725
2      12     1193  ...  Drama              1725
3      15     1193  ...  Drama              1725
4      17     1193  ...  Drama              1725

[5 rows x 7 columns]

In [ ]:
rating_popular_movie.shape

(977839, 7)

In [ ]:
## First lets create a Pivot matrix

movie_features_df=rating_popular_movie.pivot_table(index='title',columns='userId',values='rating').fillna(0)
movie_features_df.head()

userId                             1     2     3     ...  6038  6039  6040
title                                                ...                  
'Night Mother (1986)              0.000 0.000 0.000  ... 0.000 0.000 0.000
'Til There Was You (1997)         0.000 0.000 0.000  ... 0.000 0.000 0.000
'burbs, The (1989)                0.000 0.000 0.000  ... 0.000 0.000 0.000
...And Justice for All (1979)     0.000 0.000 0.000  ... 0.000 0.000 0.000
10 Things I Hate About You (1999) 0.000 0.000 0.000  ... 0.000 0.000 0.000

[5 rows x 6040 columns]

In [ ]:
from scipy.sparse import csr_matrix

movie_features_df_matrix = csr_matrix(movie_features_df.values)

from sklearn.neighbors import NearestNeighbors


model_knn = NearestNeighbors(metric = 'cosine', algorithm = 'brute')
model_knn.fit(movie_features_df_matrix)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [ ]:
movie_features_df.shape

(2514, 6040)

In [ ]:
query_index = np.random.choice(movie_features_df.shape[0])
print(query_index)
distances, indices = model_knn.kneighbors(movie_features_df.iloc[query_index,:].values.reshape(1, -1), n_neighbors = 8)


888


In [ ]:

movie_features_df.head()

userId                             1     2     3     ...  6038  6039  6040
title                                                ...                  
'Night Mother (1986)              0.000 0.000 0.000  ... 0.000 0.000 0.000
'Til There Was You (1997)         0.000 0.000 0.000  ... 0.000 0.000 0.000
'burbs, The (1989)                0.000 0.000 0.000  ... 0.000 0.000 0.000
...And Justice for All (1979)     0.000 0.000 0.000  ... 0.000 0.000 0.000
10 Things I Hate About You (1999) 0.000 0.000 0.000  ... 0.000 0.000 0.000

[5 rows x 6040 columns]

In [ ]:
store_movies=[]
for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(movie_features_df.index[query_index]))
    else:
        print('{0}: {1}, with distance of {2}:'.format(i, movie_features_df.index[indices.flatten()[i]], distances.flatten()[i]))
        store_movies.append(movie_features_df.index[indices.flatten()[i]])
print(store_movies)

Recommendations for Gaslight (1944):

1: Suspicion (1941), with distance of 0.5695535688659554:
2: Spellbound (1945), with distance of 0.5903068762720316:
3: Dial M for Murder (1954), with distance of 0.5996200960498748:
4: Lady Vanishes, The (1938), with distance of 0.606511973910324:
5: Laura (1944), with distance of 0.6106070451264572:
6: Arsenic and Old Lace (1944), with distance of 0.6289785624209019:
7: Rebecca (1940), with distance of 0.6378089287096365:
['Suspicion (1941)', 'Spellbound (1945)', 'Dial M for Murder (1954)', 'Lady Vanishes, The (1938)', 'Laura (1944)', 'Arsenic and Old Lace (1944)', 'Rebecca (1940)']


In [ ]:
''' !wget "http://files.grouplens.org/datasets/movielens/ml-100k.zip"
!unzip ml-100k.zip
!ls '''

' !wget "http://files.grouplens.org/datasets/movielens/ml-100k.zip"\n!unzip ml-100k.zip\n!ls '

###ML-1M

##Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.parallel
import torch.optim as optim
import torch.utils.data
from torch.autograd import Variable

## Importing the dataset


In [ ]:
# We won't be using these dataset.
movies = pd.read_csv('ml-1m/movies.dat', sep = '::', header = None, engine = 'python', encoding = 'latin-1')
users = pd.read_csv('ml-1m/users.dat', sep = '::', header = None, engine = 'python', encoding = 'latin-1')
ratings = pd.read_csv('ml-1m/ratings.dat', sep = '::', header = None, engine = 'python', encoding = 'latin-1')
movies.columns=(['Id','Name','Genre'])
movies.head()


Id                                Name                         Genre
0   1                    Toy Story (1995)   Animation|Children's|Comedy
1   2                      Jumanji (1995)  Adventure|Children's|Fantasy
2   3             Grumpier Old Men (1995)                Comedy|Romance
3   4            Waiting to Exhale (1995)                  Comedy|Drama
4   5  Father of the Bride Part II (1995)                        Comedy

In [ ]:
users.columns=(['Id','Gender','Age Range','Occupation','Zip Code']) ##see documentation of movielens 1-m
users.head()                                                         ## https://files.grouplens.org/datasets/movielens/ml-1m-README.txt


Id Gender  Age Range  Occupation Zip Code
0   1      F          1          10    48067
1   2      M         56          16    70072
2   3      M         25          15    55117
3   4      M         45           7    02460
4   5      M         25          20    55455

In [ ]:
ratings.columns=(['Id','MovieID','Rating','TimeStamp'])
ratings.head()

Id  MovieID  Rating  TimeStamp
0   1     1193       5  978300760
1   1      661       3  978302109
2   1      914       3  978301968
3   1     3408       4  978300275
4   1     2355       5  978824291

## Preparing the training set and the test set


In [ ]:
training_set = pd.read_csv('ml-100k/u1.base', delimiter = '\t')
training_set = np.array(training_set, dtype = 'int')
test_set = pd.read_csv('ml-100k/u1.test', delimiter = '\t')
test_set = np.array(test_set, dtype = 'int')

In [ ]:
print(training_set) ##   user id | item id | rating | timestamp. 

[[        1         2         3 876893171]
 [        1         3         4 878542960]
 [        1         4         3 876893119]
 ...
 [      943      1188         3 888640250]
 [      943      1228         3 888640275]
 [      943      1330         3 888692465]]


## Getting the number of users and movies


In [ ]:
nb_users = int(max(max(training_set[:, 0], ), max(test_set[:, 0])))
nb_movies = int(max(max(training_set[:, 1], ), max(test_set[:, 1])))

In [ ]:
''' def convert(data):
  new_data=[]
  for id_users in range(1,nb_users+1):
    id_movies=data[:,1][data[:,0]==id_users]
    id_ratings=data[:,2][data[:,0]==id_users]
    
  ratings=np.zeros(nb_movies)
  print(ratings)
training_set = convert(training_set)
 '''


' def convert(data):\n  new_data=[]\n  for id_users in range(1,nb_users+1):\n    id_movies=data[:,1][data[:,0]==id_users]\n    id_ratings=data[:,2][data[:,0]==id_users]\n    \n  ratings=np.zeros(nb_movies)\n  print(ratings)\ntraining_set = convert(training_set)\n '

## Converting the data into an array with users in lines and movies in columns


In [ ]:
def convert(data):
  new_data = []
  for id_users in range(1, nb_users + 1):
    id_movies = data[:, 1] [data[:, 0] == id_users]
    id_ratings = data[:, 2] [data[:, 0] == id_users]
    ratings = np.zeros(nb_movies)
    ratings[id_movies - 1] = id_ratings
    new_data.append(list(ratings))
  return new_data
training_set = convert(training_set)
test_set = convert(test_set)



## Converting the data into Torch tensors


In [ ]:
training_set = torch.FloatTensor(training_set)
test_set = torch.FloatTensor(test_set)
print(training_set)


tensor([[0., 3., 4.,  ..., 0., 0., 0.],
        [4., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [5., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 5., 0.,  ..., 0., 0., 0.]])


## Converting the ratings into binary ratings 1 (Liked) or 0 (Not Liked)


In [ ]:
training_set[training_set == 0] = -1
training_set[training_set == 1] = 0
training_set[training_set == 2] = 0
training_set[training_set >= 3] = 1
test_set[test_set == 0] = -1
test_set[test_set == 1] = 0
test_set[test_set == 2] = 0
test_set[test_set >= 3] = 1

In [ ]:
print(training_set)

tensor([[-1.,  1.,  1.,  ..., -1., -1., -1.],
        [ 1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.],
        ...,
        [ 1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.],
        [-1.,  1., -1.,  ..., -1., -1., -1.]])


## Creating the architecture of the Neural Network


In [ ]:
  class RMSELoss():
    def __init__(self, eps=1e-6):
        super().__init__()
        self.mse = nn.MSELoss()
        self.eps = eps
        
    def forward(self,yhat,y):
       
        loss = (torch.sqrt(self.mse(yhat,y) + self.eps))
        return torch.abs(loss)
  rmse=RMSELoss()

In [ ]:
class RBM():
  def __init__(self, nv, nh):
    self.W = torch.randn(nh, nv)
    self.a = torch.randn(1, nh)
    self.b = torch.randn(1, nv)
  def sample_h(self, x):
    wx = torch.mm(x, self.W.t())
    activation = wx + self.a.expand_as(wx)
    p_h_given_v = torch.sigmoid(activation)
    return p_h_given_v, torch.bernoulli(p_h_given_v)
  def sample_v(self, y):
    wy = torch.mm(y, self.W)
    activation = wy + self.b.expand_as(wy)
    p_v_given_h = torch.sigmoid(activation)
    return p_v_given_h, torch.bernoulli(p_v_given_h)
  def train(self, v0, vk, ph0, phk):
    self.W += (torch.mm(v0.t(), ph0) - torch.mm(vk.t(), phk)).t()
    self.b += torch.sum((v0 - vk), 0)
    self.a += torch.sum((ph0 - phk), 0)
nv = len(training_set[0])
nh = 100
batch_size = 10
rbm = RBM(nv, nh)

In [ ]:
print(training_set)

tensor([[-1.,  1.,  1.,  ..., -1., -1., -1.],
        [ 1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.],
        ...,
        [ 1., -1., -1.,  ..., -1., -1., -1.],
        [-1., -1., -1.,  ..., -1., -1., -1.],
        [-1.,  1., -1.,  ..., -1., -1., -1.]])


## Training the RBM


In [ ]:
nb_epoch = 50
for epoch in range(1, nb_epoch + 1):
  train_loss = 0
  s = 0.
  for id_user in range(0, nb_users - batch_size, batch_size):
    vk = training_set[id_user : id_user + batch_size]
    v0 = training_set[id_user : id_user + batch_size]
    ph0,_ = rbm.sample_h(v0)
    for k in range(10):
      _,hk = rbm.sample_h(vk)
      _,vk = rbm.sample_v(hk)
      vk[v0<0] = v0[v0<0]
    phk,_ = rbm.sample_h(vk)
    rbm.train(v0, vk, ph0, phk)
   
    train_loss += torch.mean(torch.abs(v0[v0 >= 0] - vk[v0 >= 0]))
    loss= rmse.forward(v0[v0 >= 0] ,vk[v0 >= 0])
    s += 1.
  print('epoch: '+str(epoch)+' loss: '+str(train_loss/s)+ ' RMSE:'+str(loss))


epoch: 1 loss: tensor(0.2791) RMSE:tensor(0.4838)
epoch: 2 loss: tensor(0.2492) RMSE:tensor(0.4747)
epoch: 3 loss: tensor(0.2511) RMSE:tensor(0.4838)
epoch: 4 loss: tensor(0.2512) RMSE:tensor(0.4701)
epoch: 5 loss: tensor(0.2486) RMSE:tensor(0.5007)
epoch: 6 loss: tensor(0.2505) RMSE:tensor(0.4856)
epoch: 7 loss: tensor(0.2483) RMSE:tensor(0.4883)
epoch: 8 loss: tensor(0.2487) RMSE:tensor(0.5007)
epoch: 9 loss: tensor(0.2484) RMSE:tensor(0.4998)
epoch: 10 loss: tensor(0.2487) RMSE:tensor(0.4910)
epoch: 11 loss: tensor(0.2497) RMSE:tensor(0.5084)
epoch: 12 loss: tensor(0.2486) RMSE:tensor(0.5050)
epoch: 13 loss: tensor(0.2484) RMSE:tensor(0.4645)
epoch: 14 loss: tensor(0.2468) RMSE:tensor(0.4901)
epoch: 15 loss: tensor(0.2470) RMSE:tensor(0.4756)
epoch: 16 loss: tensor(0.2482) RMSE:tensor(0.4901)
epoch: 17 loss: tensor(0.2470) RMSE:tensor(0.4892)
epoch: 18 loss: tensor(0.2470) RMSE:tensor(0.4980)
epoch: 19 loss: tensor(0.2481) RMSE:tensor(0.4874)
epoch: 20 loss: tensor(0.2468) RMSE:tens

## Testing the RBM


In [ ]:
test_loss = 0
s = 0.
rmse=0
users=nb_users
for id_user in range(nb_users):
    v = training_set[id_user:id_user+1]
    vt = test_set[id_user:id_user+1]
    if len(vt[vt>=0]) > 0:
        _,h = rbm.sample_h(v)
        _,v = rbm.sample_v(h)
        test_loss += torch.mean(torch.abs(vt[vt>=0] - v[vt>=0]))
        loss= torch.sqrt(test_loss)
        s += 1.
print('test loss: '+str(test_loss/s) +"RMSE:"+str(loss))

test loss: tensor(0.2467)RMSE:tensor(10.6420)
